
question_data = [
    {"category": "Entertainment: Video Games",
     "type": "boolean",
     "difficulty": "easy",
     "question": "The name of the main character of the video game 'The Legend of Zelda', is Zelda.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Mythology", "type": "boolean", "difficulty": "easy",
     "question": "In Norse mythology, Thor once dressed as a woman.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
     "question": "Han Solo&#039;s co-pilot and best friend, &quot;Chewbacca&quot;, "
                 "is an Ewok.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "History", "type": "boolean", "difficulty": "easy",
     "question": "The Cold War ended with Joseph Stalin&#039;s death.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "History", "type": "boolean", "difficulty": "easy",
     "question": "The Tiananmen Square protests of 1989 were held in Hong Kong.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
     "question": "The music video to The Buggle&#039;s &quot;Video Killed the Radio "
                 "Star&quot; was the first music video to broadcast on MTV.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Geography", "type": "boolean", "difficulty": "easy",
     "question": "Greenland is covered with grass and Iceland covered with ice.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "History", "type": "boolean", "difficulty": "easy",
     "question": "The Spitfire originated from a racing plane.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
     "question": "Linus Torvalds created Linux and Git.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
     "question": "The logo for Snapchat is a Bell.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "question": "There are 6 legendary cards in &quot;Clash Royale&quot;.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean",
     "difficulty": "easy",
     "question": "Studio Ghibli is a Japanese animation studio responsible for the "
                 "films &quot;Wolf Children&quot; and &quot;The Boy and the "
                 "Beast&quot;.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean",
     "difficulty": "easy",
     "question": "In Kill La Kill, the weapon of the main protagonist is a katana. ",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "A scientific study on peanuts in bars found traces of over 100 "
                 "unique specimens of urine.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Science: Gadgets", "type": "boolean", "difficulty": "easy",
     "question": "The communication protocol NFC stands for Near-Field Control.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
     "question": "Samuel L. Jackson had the words, &#039;Bad Motherf*cker&#039; "
                 "in-scripted on his lightsaber during the filming of Star Wars.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Board Games", "type": "boolean", "difficulty": "easy",
     "question": "The Angry Video Game Nerd&#039;s alter ego is &quot;Board "
                 "James&quot;.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Animals", "type": "boolean", "difficulty": "easy",
     "question": "Rabbits are rodents.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Entertainment: Board Games", "type": "boolean", "difficulty": "easy",
     "question": "There is a Donald Trump Board Game, which was made in 1989.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
     "question": "In most programming languages, the operator ++ is equivalent to "
                 "the statement &quot;+= 1&quot;.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "question": "Ana was added as a new hero for the game Overwatch on July 19th, "
                 "2016.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Science & Nature", "type": "boolean", "difficulty": "easy",
     "question": "An Astronomical Unit is the distance between Earth and the Moon.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Politics", "type": "boolean", "difficulty": "easy",
     "question": "One of Barack Obama&#039;s United States presidential campaign "
                 "slogan&#039;s was &quot;Yes We Can&quot;.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
     "question": "Daft Punk originated in France.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Celebrities", "type": "boolean", "difficulty": "easy",
     "question": "Marilyn Monroe was born on July 1, 1926.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "question": "In &quot;Undertale&quot;, the main character of the game is Sans.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
     "question": "&quot;Minions&quot; was released on the June 10th, 2015.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "History", "type": "boolean", "difficulty": "easy",
     "question": "Adolf Hitler was tried at the Nuremberg trials.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "question": "Valve&#039;s &quot;Portal&quot; and &quot;Half-Life&quot; "
                 "franchises exist within the same in-game universe.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
     "question": "Linux was first created as an alternative to Windows XP.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
     "question": "Scatman John&#039;s real name was John Paul Larkin.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "question": "In Heroes of the Storm, the Cursed Hollow map gimmick requires "
                 "players to kill the undead to curse the enemy team.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Television", "type": "boolean", "difficulty": "easy",
     "question": "In &quot;Star Trek&quot;, Klaang is a typical Klingon male.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Science & Nature", "type": "boolean", "difficulty": "easy",
     "question": "An average human can go two weeks without water.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Art", "type": "boolean", "difficulty": "easy",
     "question": "Leonardo da Vinci was not the creator of the Mona Lisa.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "&quot;27 Club&quot; is a term used to refer to a list of famous "
                 "actors, musicians, and artists who died at the age of 27.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Geography", "type": "boolean", "difficulty": "easy",
     "question": "Hungary is the only country in the world beginning with H.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean",
     "difficulty": "easy",
     "question": "In the &quot;To Love-Ru&quot; series, Golden Darkness is sent to "
                 "kill Lala Deviluke.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Science: Mathematics", "type": "boolean", "difficulty": "easy",
     "question": "The sum of any two odd integers is odd.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Science & Nature", "type": "boolean", "difficulty": "easy",
     "question": "Psychology is the science of behavior and mind.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean",
     "difficulty": "easy",
     "question": "In Chobits, Hideki found Chii in his apartment.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Politics", "type": "boolean", "difficulty": "easy",
     "question": "Former president Theodore Roosevelt (1900-1908)  ran for another "
                 "term under the Progressive Party in 1912.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "question": "In the &quot;S.T.A.L.K.E.R.&quot; series, the Freedom faction "
                 "wishes to destroy the supernatural area known as  &quot;the "
                 "Zone&quot;.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Geography", "type": "boolean", "difficulty": "easy",
     "question": "Rhode Island is actually located on the US mainland, despite its "
                 "name.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
     "question": "John Williams composed the music for &quot;Star Wars&quot;.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "question": "In Until Dawn, both characters Sam and Mike cannot be killed under "
                 "any means until the final chapter of the game.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
     "question": "The Python programming language gets its name from the British "
                 "comedy group &quot;Monty Python.&quot;",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "question": "The game &quot;Jetpack Joyride&quot; was created by &quot;Redbrick "
                 "Studios&quot;.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
     "question": "Lead Singer Rivers Cuomo of American rock band Weezer attended "
                 "Harvard.",
     "correct_answer": "True", "incorrect_answers": ["False"]}
]
question_data_1 = [
{"text": "A slug's blood is green.", "answer": "True"},
{"text": "The loudest animal is the African Elephant.", "answer": "False"},
{"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
{"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
{"text": "In West Virginia, USA, if you accidentally hit an animal with your car, you are free to take it home to eat.", "answer": "True"},
{"text": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.", "answer": "False"},
{"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
{"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
{"text": "Google was originally called 'Backrub'.", "answer": "True"},
{"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
{"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
{"text": "A few ounces of chocolate can to kill a small dog.", "answer": "True"}
]